Login logout
DragisaDraskovic/Library-Praksa pull request #3
Opened 2023-03-09 14:02 UTC by DragisaDraskovic

Finish login/logout task

2023-03-09 15:53 UTC, SaleBojke requested changes

2023-03-09 15:53 UTC, SaleBojke commented on src/components/login/Login.tsx
>        <p className='wellcome_to_library'>Wellcome to library</p>
typo, welcome*

2023-03-09 15:53 UTC, SaleBojke commented on src/components/login/Login.css
> +    font-size: unset;
zasto font-size: unset?

2023-03-09 15:53 UTC, SaleBojke commented on src/services/TokenService.tsx
> +const deleteLocasStorage = () => {
typo, deleteLocalStorage*

2023-03-09 15:53 UTC, SaleBojke commented on src/route-config.ts
> +  // { path: '/login', component: Login },
ukloni zakomentarisan kod, ne zelimo da zakomentarisan kod zavrsi na masteru.

2023-03-09 15:53 UTC, SaleBojke commented on src/route-config.ts
> +  // { path: '*', component: Login }
isto

2023-03-09 15:53 UTC, SaleBojke commented on src/model/LoginResponse.tsx
> +    refreshToken: string
mozda bolje refreshAccessToken?

2023-03-09 15:53 UTC, SaleBojke commented on src/components/mainPage/MainPage.tsx
> +      <Card />
kako bi prikazao 75.000 kartica?

2023-03-09 15:53 UTC, SaleBojke commented on src/components/login/Login.tsx
> +          onChange={({ target }) => setUsername(target.value)}
👌

2023-03-09 15:53 UTC, SaleBojke commented on src/components/login/Login.tsx
> +          placeholder='Entrer username'
typo, enter*

2023-03-09 15:53 UTC, SaleBojke commented on src/components/header/Header.tsx
> +        <p onClick={handleLogout}>Logout <LogoutIcon/></p>
zasto <p>, a ne button?

2023-03-09 15:53 UTC, SaleBojke commented on src/components/header/Header.css
> +        margin-left: 1200px;
ikonica moze da se premeseti na desnu stranu na drugaciji nacin, margina od 1200px  nije resenje. A koliko vidim nigde se ni ne koristi ova klasa.

2023-03-09 15:53 UTC, SaleBojke commented on src/components/header/Header.css
> +    .logut_icon {
typo, .logout_icon*

2023-03-09 15:53 UTC, SaleBojke commented on src/components/header/Header.css
> +.logut_icon {
typo, logout_icon*

2023-03-09 16:01 UTC, bushinSandra requested changes

2023-03-09 16:01 UTC, sandra-matkovic-valcon commented on src/components/header/Header.css
> +    margin-left: 300px;
Da li ti zaista treba ovako velika margina? Mozda bi ovo moglo malo drugacije da se resi

2023-03-09 16:01 UTC, sandra-matkovic-valcon commented on src/components/header/Header.css
> +        margin-left: 1200px;
Opet isti problem, 1200px je previse za marginu, trebalo bi to drugacije pozicionirati umesto sto zakucavas tolike margine

2023-03-09 16:01 UTC, sandra-matkovic-valcon commented on src/components/header/Header.tsx
> +    TokenService.deleteLocasStorage()
Imas typo ovde

2023-03-09 16:01 UTC, sandra-matkovic-valcon commented on src/components/header/Header.tsx
> +      <div className='logut_icon'>
Da li ti treba ovaj div ako su ti i text i ikonica grupisani p tagom? Mozda je button tag malo intuitivniji nego p tag sa onClick?

2023-03-09 16:01 UTC, sandra-matkovic-valcon commented on src/components/login/Login.css
> +    .blur_for_input {
Visak? Izbrgavaj da komitujes prazne blokove ili zakomentarisan kod

2023-03-09 16:01 UTC, sandra-matkovic-valcon commented on src/components/mainPage/MainPage.tsx
>        <Card />
Najbolje bi bilo da imas neku petlju kojom ces izrenderovati neki br komponenata, ne kopirati ovako komponente..
Posle ces prolaziti kroz niz podataka i prosledjivati podatke...

2023-03-09 16:01 UTC, sandra-matkovic-valcon commented on src/route-config.ts
> +
Nemoj ostavljati zakomentarisan kod

2023-03-09 16:01 UTC, bushinSandra commented on src/services/LoginService.tsx
> +const baseUrl = 'https://library-practice-app.azurewebsites.net'
izdvoji baseUrl u poseban file ili u .env file, trebace ti i za druge requestove

2023-03-09 16:17 UTC, DragisaDraskovic commented on src/components/login/Login.css
> +    font-size: unset;
Kada sam probao da stilizujem teks naisao sam na tu funkciju i primenio je. Obrisao sam je i dodatno izmenio tu klasu.

2023-03-09 16:18 UTC, DragisaDraskovic commented on src/services/TokenService.tsx
> +const deleteLocasStorage = () => {
Ispravio.

2023-03-09 16:19 UTC, DragisaDraskovic commented on src/route-config.ts
> +  // { path: '/login', component: Login },
Zaboravio sam. Ispravljeno.

2023-03-09 16:19 UTC, DragisaDraskovic commented on src/route-config.ts
> +  // { path: '*', component: Login }
Ispravljeno.

2023-03-09 16:20 UTC, DragisaDraskovic commented on src/components/login/Login.tsx
> +          placeholder='Entrer username'
Ispravljeno.

2023-03-09 16:28 UTC, DragisaDraskovic commented on src/components/header/Header.tsx
> +        <p onClick={handleLogout}>Logout <LogoutIcon/></p>
Bilo mi je lakse da ikonicu ubacim u p tagove. Prepravio sam.

2023-03-09 16:30 UTC, DragisaDraskovic commented on src/components/header/Header.css
> +        margin-left: 1200px;
To sam nesto testirao. Obrisao sam tu klasu posto je nigde ne koristim.

2023-03-09 16:30 UTC, DragisaDraskovic commented on src/components/header/Header.css
> +    .logut_icon {
Ova klasa se takodje ne koristi nigde pa sam je obirsao.

2023-03-09 16:31 UTC, DragisaDraskovic commented on src/components/header/Header.css
> +.logut_icon {
Takodje se nigde ne koristi ova klasa pa sam je obrisao.

2023-03-09 16:35 UTC, DragisaDraskovic commented on src/components/header/Header.css
> +    margin-left: 300px;
Resio sam ovo na drugaciji nacin. Sada sam ikonicu ubacio unutar dugmeta umesto unutar p taga i njenu poziciju namestam tako sto pozicioniram dugme u kome se nalazi. U klasi za dugme setovao sam position: relativ i right:10px da bi mi se dugme malo odvojilo od desne ivice, time sam simulirao marginu ako je to ok.

2023-03-09 16:36 UTC, DragisaDraskovic commented on src/components/header/Header.css
> +        margin-left: 1200px;
Ova klasa je takodje obrisana posto mi vise nije potrebna.

2023-03-09 16:38 UTC, DragisaDraskovic commented on src/components/header/Header.tsx
> +      <div className='logut_icon'>
Prepravio sam, umesto p taga stavio sam button

2023-03-09 16:39 UTC, DragisaDraskovic commented on src/components/login/Login.css
> +    .blur_for_input {
Ova klasa .blur_for_input sluzila je za blur-ove koje sam uklonio, tako da je sada i ova klasa obrisana.

2023-03-09 16:41 UTC, DragisaDraskovic commented on src/components/mainPage/MainPage.tsx
>        <Card />
Ok, to mi je jasno. Za potrebe testiranja layouta moram sam rucno da zakucam sto vise Card komponenti. Kada bude dobijao podatke sa beck-a resicu ovaj problem na drugaciji nacin.

2023-03-09 16:46 UTC, DragisaDraskovic commented on src/components/header/Header.tsx
> +    TokenService.deleteLocasStorage()
Ispravio sam.

2023-03-09 16:46 UTC, DragisaDraskovic commented on src/route-config.ts
> +
Zaboravio sam da prodjem kroz ovaj fajl pre commit-a. Ispravio sam.

2023-03-09 16:47 UTC, DragisaDraskovic commented on src/services/LoginService.tsx
> +const baseUrl = 'https://library-practice-app.azurewebsites.net'
Ok. Ispravio sam.

2023-03-09 17:21 UTC, DragisaDraskovic commented
Izmenio sam jos neke stvari dodatno zbog samo izgleda.

2023-03-10 08:47 UTC, sandra-matkovic-valcon commented on src/components/mainPage/MainPage.tsx
>        <Card />
Na main granu ne bi trebalo da ide nista sto je za potrebe testiranja, sve sto je za potrebe testiranja brise se pre spajanja na main i main je uvek spreman kao da ce u produkciju

2023-03-10 08:49 UTC, bushinSandra commented on src/route-config.ts
> +
Mozes i kad napravis PR, pre nego sto prevuces na In review da prodjes kroz svoj PR i pregledas promene, kao da sebi radis review, tako ces najlakse videti greske i viskove

2023-03-10 08:55 UTC, bushinSandra requested changes

2023-03-10 08:55 UTC, bushinSandra commented on src/components/mainPage/MainPage.tsx
> +      <Card />
Fakujes array sa 75000 knjiga?

2023-03-10 09:19 UTC, bushinSandra approved these changes
Review ok, you can merge

2023-03-10 09:20 UTC, DragisaDraskovic commented on src/components/mainPage/MainPage.tsx
>        <Card />
Obrisao sam Card komponente.

2023-03-10 09:21 UTC, merged